name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-check-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version-file: '.node-version'
    - name: Setup just
      uses: extractions/setup-just@v3
      with:
        enable-cache: true
    - name: Install dependencies
      run: |
        npm install
    - name: Lint, Test, Build
      run: |
        npm run ci

